webtalk_init -webtalk_dir /home/sfarhat/Bureau/Projet Systme_info 23/Microprocessor/Version2/Microprocessor/Microprocessor.sim/sim_1/behav/xsim/xsim.dir/MICROPROCESSOR_TEST_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue May 30 13:14:53 2023" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2258646" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "89f259de-ec28-4e83-bf41-24b8acd73187" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "8dc54fb708904ee99b5423ecaa1a5ca5" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "144" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 20.04.6 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3200.000 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "67.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "3" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.02_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "122656_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3205832737 -regid "" -xml /home/sfarhat/Bureau/Projet Systme_info 23/Microprocessor/Version2/Microprocessor/Microprocessor.sim/sim_1/behav/xsim/xsim.dir/MICROPROCESSOR_TEST_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/sfarhat/Bureau/Projet Systme_info 23/Microprocessor/Version2/Microprocessor/Microprocessor.sim/sim_1/behav/xsim/xsim.dir/MICROPROCESSOR_TEST_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/sfarhat/Bureau/Projet Systme_info 23/Microprocessor/Version2/Microprocessor/Microprocessor.sim/sim_1/behav/xsim/xsim.dir/MICROPROCESSOR_TEST_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
